version: '3'

volumes:
  postgres_volume:

services:
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - ./static:/static
    command: sh -c "chmod +x init_data.sh
               && ./init_data.sh
               && python manage.py collectstatic --no-input
               && gunicorn resume.wsgi:application --workers=3 --access-logfile - --bind 0.0.0.0:${PORT}"
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: "on-failure"
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    env_file:
      - .env
    image: postgres:13.3
    container_name: ${DATABASES_HOST}
    restart: always
    environment:
      POSTGRES_DB: ${DATABASES_NAME}
      POSTGRES_USER: ${DATABASES_USER}
      POSTGRES_PASSWORD: ${DATABASES_PASSWORD}
    volumes:
      - postgres_volume:/data/db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./static:/static
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - backend
