# Generated by Django 4.2.1 on 2023-05-28 19:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'не ищет работу'), (1, 'в активном поиске')])),
                ('grade', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11)),
                ('education', models.CharField(max_length=250)),
                ('experience', models.TextField()),
                ('portfolio', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
    ]
